### ISSUE TITLE
unsupported protocol scheme on record creation

### ISSUE THREAD

**Issue by di-rect** [caddy-dns/powerdns#1]
I'm migrating from Traefik to Caddy and I always had a working Traefik to my PowerDNS server API for creating the needed acme records. At the moment I get this on caddy:

`
| {"level":"error","ts":17135456667.9905512,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"*.domain.tld","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[*.domain.tld] solving challenges: presenting for challenge: adding temporary record for zone \"domain.tld.\": Get \"my.dns.tld:8081/api/v1/servers/localhost/zones?zone=domain.tld.\": unsupported protocol scheme \"my.dns.tld\" (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/168320304/52825046623) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
`

And on my PowerDNS AUTH server at the same time:

```
Dec 09 02:11:04 Lua record monitoring declaring TCP/IP 123.123.123.123:443 DOWN: connecting to 123.123.123.123:443 failed: Connection refused
Dec 09 02:11:09 Lua record monitoring declaring TCP/IP 123.123.123.123;443 UP!
```
Why would this happen that PowerDNS wants to connect to my webserver when it's dns-01 ?

**Comment by nickygerritsen** [comment]
Did you set your `server_url` to `my.dns.tld:8081`? Could you try `http://my.dns.tld:8081` (or `https` if it uses HTTPS)?
